# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - cd website && yarn install && yarn build && GIT_USER='${GH_NAME}' CURRENT_BRANCH=master yarn run publish-gh-pages