backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "website/static/images/uploads" # Media files will be stored in the repo under images
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "../../../blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Url", name: "Author Url", widget: "string"}
  - name: "docs"
    label: "Docs"
    folder: "../../../../docs"
    create: true
    fields:
      - {label: "id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar label", name: "sidebar_label", widget: "string"}